'use strict'
module.exports = {
  USER_CONNECTED: "USER_CONNECTED",
  RESET_DEFAULT_CHAT: "RESET_DEFAULT_CHAT",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  MESSAGE_SENT: "MESSAGE_SENT",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  TYPING: "TYPING",
  VERIFY_USER: "VERIFY_USER",
  LOG_OUT: "LOG_OUT",
  PRIVATE_MESSAGE: "PRIVATE_MESSAGE"
}