const authActionTypes = {
  LOG_IN_REQUEST: 'LOG_IN_REQUEST',
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
  LOG_IN_FAILURE: 'LOG_IN_REQUEST',
  AUTHORIZE_REQUEST: 'AUTHORIZE_REQUEST',
  AUTHORIZE_SUCCESS: 'AUTHORIZE_SUCCESS',
  AUTHORIZE_FAILURE: 'AUTHORIZE_FAILURE',
};

export default authActionTypes;